version: '3'
services:
  db:
    image: postgres:11.6
    environment:
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=''
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  guard:
    build: .
    command: bundle exec guard --no-interactions
    tty: true
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: test
    # depends_on:
    #   - db
